version: "3.3"

services:
    # create mongodb docker 
    mongodb:
      image: mongo:latest
      container_name: mongodb
      environment:
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: adminmongo17x
      ports:
        - 27017:27017
      volumes:
        - .dbmongodb:/var/lib/lib/mongodb
        
      